spring.application.name=assignment2-triangle-api
server.port=8080
spring.datasource.url=jdbc:h2:mem:triangledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
